import { useState, useEffect } from "react";
import { AppLayout } from "@/components/layout/AppLayout";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Loader2, FileText, Send, Check, Download, ImageIcon, PenLine, Upload, Paperclip, X } from "lucide-react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { useNotifications } from "@/contexts/NotificationContext";
import { Capacitor } from "@capacitor/core";
import { Filesystem, Directory } from "@capacitor/filesystem";
interface WorksheetAssignment {
  id: string;
  worksheet_id: string;
  class_level: string;
  section: string;
  assigned_at: string;
  due_date: string | null;
  status: string;
  worksheets?: {
    id: string;
    subject: string;
    chapter: string | null;
    topic: string | null;
    subtopic: string | null;
    worksheet_content: string;
    image_url: string | null;
    page_count: number | null;
    academic_year: string | null;
  } | null;
}

// Splits worksheet_content into individual activities on '---',
// strips the COMPLETE ANSWER KEY section so students never see answers.
function parseWorksheetActivities(content: string): string[] {
  if (!content) return [];
  const keyIndex = content.search(/COMPLETE ANSWER KEY/i);
  const studentFacing = keyIndex >= 0 ? content.slice(0, keyIndex) : content;
  return studentFacing
    .split(/^---$/m)
    .map((block) => block.trim())
    .filter((block) => block.length > 0);
}

// (Per-worksheet submission lookup is now derived from the batch
// `mySubmissions` query inside the component, via getSubmissionFor().)

async function downloadWorksheetPDF(ws: WorksheetAssignment, profile: any) {
  const content = ws.worksheets?.worksheet_content || "";
  const topic = ws.worksheets?.topic || "Worksheet";
  let html = content
    .replace(/^#### (.*?)$/gm, "<h4></h4>")
    .replace(/^### (.*?)$/gm, "<h3></h3>")
    .replace(/^## (.*?)$/gm, "<h2></h2>")
    .replace(/^# (.*?)$/gm, "<h1></h1>")
    .replace(/\*\*(.*?)\*\*/g, "<strong></strong>")
    .replace(/^---$/gm, "<hr>")
    .replace(/^- (.*?)$/gm, "<li></li>")
    .replace(/((?:<li>.*?<\/li>\n?)+)/g, "<ul></ul>");
  html = html.split("\n\n").map((p: string) => {
    const t = p.trim();
    if (!t || t.startsWith("<h") || t.startsWith("<ul") || t.startsWith("<hr")) return t;
    return "<p>" + t.replace(/\n/g, "<br>") + "</p>";
  }).join("\n");
  const tempDiv = document.createElement("div");
  tempDiv.innerHTML = `<div class="report"><div class="header"><div class="header-left"><div class="brand">APAS <span>Worksheet</span></div><div class="report-label">Practice Worksheet</div></div><div class="header-right"><div class="report-date">${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</div><div class="status-badge">AI Generated</div></div></div><div class="learner-card"><div class="lc-field"><label>Class</label><value>Class ${profile?.class_grade || ""}</value><small>Section ${profile?.section || ""}</small></div><div class="lc-field"><label>Subject</label><value>${ws.worksheets?.subject || ""}</value><small>${topic}</small></div><div class="lc-field"><label>Report Type</label><value>Worksheet</value><small>Practice Activities</small></div></div><div class="content">${html}</div><div class="footer"><div class="footer-note">This worksheet is auto-generated by the APAS AI engine. For academic use only.</div><div class="footer-apas">APAS &copy; ${new Date().getFullYear()}</div></div></div>`;
  const styleEl = document.createElement("style");
  styleEl.textContent = "* { box-sizing: border-box; margin: 0; padding: 0; font-family: Arial, sans-serif; } .report { max-width: 780px; margin: 0 auto; padding: 28px 24px; color: #1a1a2e; font-size: 12px; line-height: 1.6; } .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; padding-bottom: 18px; border-bottom: 2px solid #1a1a2e; } .brand { font-size: 24px; color: #1a1a2e; font-weight: bold; } .brand span { color: #0e9a7b; font-style: italic; } .report-label { font-size: 10px; font-weight: 600; letter-spacing: 2px; text-transform: uppercase; color: #6b6b8a; margin-top: 4px; } .header-right { text-align: right; } .report-date { font-size: 12px; color: #3a3a5c; } .status-badge { display: inline-block; background: #0e9a7b; color: white; font-size: 9px; font-weight: 600; letter-spacing: 1.5px; text-transform: uppercase; padding: 3px 10px; border-radius: 20px; margin-top: 4px; } .learner-card { background: #1a1a2e; color: white; border-radius: 12px; padding: 20px 24px; margin-bottom: 24px; display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 16px; } .lc-field label { font-size: 9px; font-weight: 600; letter-spacing: 1.5px; text-transform: uppercase; color: rgba(255,255,255,0.45); display: block; margin-bottom: 3px; } .lc-field value { font-size: 16px; color: white; display: block; font-weight: bold; } .lc-field small { font-size: 11px; color: rgba(255,255,255,0.55); } .content h1 { font-size: 18px; color: #1a1a2e; margin: 24px 0 10px 0; padding-bottom: 6px; border-bottom: 2px solid #0e9a7b; } .content h2 { font-size: 15px; color: #1a1a2e; margin: 20px 0 8px 0; padding-left: 12px; border-left: 4px solid #0e9a7b; } .content h3 { font-size: 13px; font-weight: 600; color: #3a3a5c; margin: 16px 0 6px 0; } .content p { margin: 6px 0; color: #3a3a5c; } .content strong { color: #1a1a2e; font-weight: 600; } .content ul { list-style: none; margin: 6px 0; padding: 0; } .content ul li { position: relative; padding-left: 20px; color: #3a3a5c; margin: 3px 0; } .content ul li:before { content: '\\25CF'; position: absolute; left: 0; color: #0e9a7b; font-weight: bold; } .content hr { border: none; border-top: 1px solid #d0d0e8; margin: 12px 0; } .footer { margin-top: 20px; padding-top: 12px; border-top: 1px solid #e0e0e8; display: flex; justify-content: space-between; font-size: 10px; color: #6b6b8a; } .footer-apas { text-align: right; font-weight: 600; }";
  tempDiv.appendChild(styleEl);
const html2pdf = (await import("html2pdf.js")).default;

const options: any = {
  margin: 10,
  filename: `Worksheet-${topic}.pdf`,
  html2canvas: {
    scale: 2,
    useCORS: true,
    backgroundColor: "#f7f5f0",
  },
  jsPDF: {
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  },
};

// Browser
if (!Capacitor.isNativePlatform()) {
  html2pdf().set(options).from(tempDiv).save();
  toast.success("Worksheet downloaded!");
  return;
}

// Android App
const worker = html2pdf().set(options).from(tempDiv);

// Generate PDF as data URI
const pdfData = await worker.outputPdf("datauristring");

// Extract Base64
const base64 = pdfData.split(",")[1];

// Save PDF
const result = await Filesystem.writeFile({
  path: `Worksheet-${topic}.pdf`,
  data: base64,
  directory: Directory.Documents,
});

console.log(result);

toast.success("Worksheet downloaded successfully!");
}

async function downloadWorksheetImage(ws: WorksheetAssignment) {
  const imageUrl = ws.worksheets?.image_url;
  if (!imageUrl) {
    toast.error("Illustrated image is still being generated. Please try again in a moment.");
    return;
  }
  try {
    const topic = ws.worksheets?.topic || "Worksheet";
    const ext = imageUrl.split(".").pop()?.split("?")[0] ?? "jpg";
    const response = await fetch(imageUrl);
    const blob = await response.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Illustrated-Worksheet-${topic}.${ext}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  } catch (err) {
    console.error("Failed to download image", err);
    toast.error("Failed to download image");
  }
}

async function verifyFileIntegrity(file: File): Promise<boolean> {
  // Reads the first bytes of the file and checks them against known
  // file-signature ("magic number") headers. Catches corrupted files,
  // truncated uploads, and files renamed to a different extension.
  const SIGNATURES: { ext: string[]; check: (bytes: Uint8Array) => boolean }[] = [
    { ext: [".pdf"], check: (b) => b[0] === 0x25 && b[1] === 0x50 && b[2] === 0x44 && b[3] === 0x46 }, // %PDF
    { ext: [".png"], check: (b) => b[0] === 0x89 && b[1] === 0x50 && b[2] === 0x4e && b[3] === 0x47 },
    { ext: [".jpg", ".jpeg"], check: (b) => b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff },
    {
      ext: [".tiff", ".tif"],
      check: (b) =>
        (b[0] === 0x49 && b[1] === 0x49 && b[2] === 0x2a && b[3] === 0x00) || // little-endian
        (b[0] === 0x4d && b[1] === 0x4d && b[2] === 0x00 && b[3] === 0x2a), // big-endian
    },
    { ext: [".docx"], check: (b) => b[0] === 0x50 && b[1] === 0x4b && (b[2] === 0x03 || b[2] === 0x05 || b[2] === 0x07) }, // PK zip
    { ext: [".doc"], check: (b) => b[0] === 0xd0 && b[1] === 0xcf && b[2] === 0x11 && b[3] === 0xe0 }, // OLE compound file
  ];

  if (file.size === 0) return false;

  const headerBlob = file.slice(0, 12);
  const buffer = await new Promise<ArrayBuffer | null>((resolve) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as ArrayBuffer);
    reader.onerror = () => resolve(null);
    reader.readAsArrayBuffer(headerBlob);
  });
  if (!buffer) return false;

  const bytes = new Uint8Array(buffer);
  const fileExt = file.name.slice(file.name.lastIndexOf(".")).toLowerCase();
  const rule = SIGNATURES.find((s) => s.ext.includes(fileExt));
  if (!rule) return false; // unknown extension, treat as failed integrity check

  try {
    return rule.check(bytes);
  } catch {
    return false;
  }
}

async function uploadAnswerFile(
  ws: WorksheetAssignment,
  file: File,
  userId: string,
  profile: any,
  existingSubmissionId: string | null | undefined
): Promise<{ url: string; name: string } | null> {
  try {
    const ext = file.name.split(".").pop() || "dat";
    const safeName = `${ws.worksheet_id}_${userId}_${Date.now()}.${ext}`;
    const { error: uploadError } = await supabase.storage
      .from("worksheet-submission-files")
      .upload(safeName, file, { upsert: true, contentType: file.type || "application/pdf" });
    if (uploadError) throw new Error(uploadError.message);

    const { data: urlData } = supabase.storage
      .from("worksheet-submission-files")
      .getPublicUrl(safeName);
    const fileUrl = urlData.publicUrl;

    if (existingSubmissionId) {
      const { error } = await supabase
        .from("worksheet_submissions")
        .update({
          answer_file_url: fileUrl,
          answer_file_name: file.name,
          status: "submitted",
          submitted_at: new Date().toISOString(),
        })
        .eq("id", existingSubmissionId);
      if (error) throw new Error(error.message);
    } else {
      const { error } = await supabase.from("worksheet_submissions").insert([
        {
          worksheet_id: ws.worksheet_id,
          assignment_id: ws.id,
          student_id: userId,
          student_name: profile?.full_name || null,
          class_level: ws.class_level,
          section: ws.section,
          school_id: profile?.school_id || null,
          answers: {},
          answer_file_url: fileUrl,
          answer_file_name: file.name,
          status: "submitted",
          submitted_at: new Date().toISOString(),
        },
      ] as any);
      if (error) throw new Error(error.message);
    }

    return { url: fileUrl, name: file.name };
  } catch (err: any) {
    console.error("Failed to upload answer file:", err);
    toast.error(`Upload failed: ${err.message || "Unknown error"}`);
    return null;
  }
}

async function removeAnswerFile(submissionId: string, fileUrl: string): Promise<boolean> {
  try {
    // Extract the storage object path from the public URL
    // Public URL format: .../storage/v1/object/public/worksheet-submission-files/<path>
    const marker = "/worksheet-submission-files/";
    const idx = fileUrl.indexOf(marker);
    if (idx >= 0) {
      const objectPath = fileUrl.slice(idx + marker.length).split("?")[0];
      const { error: removeErr } = await supabase.storage
        .from("worksheet-submission-files")
        .remove([objectPath]);
      if (removeErr) {
        console.warn("Storage removal warning (continuing anyway):", removeErr.message);
      }
    }

    const { error } = await supabase
      .from("worksheet_submissions")
      .update({ answer_file_url: null, answer_file_name: null })
      .eq("id", submissionId);
    if (error) throw new Error(error.message);

    return true;
  } catch (err: any) {
    console.error("Failed to remove answer file:", err);
    toast.error(`Failed to remove file: ${err.message || "Unknown error"}`);
    return false;
  }
}

export default function Worksheets() {
  const { user, profile } = useAuth();
  const { markWorksheetNotificationAsRead } = useNotifications();
  const queryClient = useQueryClient();

  const [practiceWorksheet, setPracticeWorksheet] = useState<WorksheetAssignment | null>(null);
  const [activityAnswers, setActivityAnswers] = useState<Record<number, string>>({});
  const [isSubmittingWorksheet, setIsSubmittingWorksheet] = useState(false);
  const [uploadingId, setUploadingId] = useState<string | null>(null);
  const [removingId, setRemovingId] = useState<string | null>(null);

  // ── Assigned Worksheets
  const { data: assignedWorksheets = [], isLoading: worksheetsLoading } = useQuery({
    queryKey: ["student-worksheets", user?.id, profile?.school_id, profile?.class_grade, profile?.section],
    enabled: !!user?.id && !!profile?.school_id && !!profile?.class_grade,
    queryFn: async () => {
      if (!profile?.class_grade) return [];
      const classLevelFormatted = `Class ${profile?.class_grade}`;

      let query = supabase
        .from("worksheet_assignments")
        .select("id, worksheet_id, class_level, section, assigned_at, due_date, status, worksheets(id, worksheet_content, image_url, page_count, chapter, topic, subtopic, academic_year, subject)")
        .eq("school_id", profile?.school_id!)
        .eq("class_level", classLevelFormatted)
        .eq("status", "active");

      if (profile?.section) {
        query = query.or(`section.eq.${profile.section},section.is.null`);
      }

      const { data, error } = await query.order("assigned_at", { ascending: false });

      if (error) {
        console.error("Error fetching worksheets:", error);
        return [];
      }
      return (data || []) as WorksheetAssignment[];
    },
  });

  // ── All of this student's own submissions (for per-card status + file display)
  const { data: mySubmissions = [] } = useQuery({
    queryKey: ["student-all-worksheet-submissions", user?.id],
    enabled: !!user?.id,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("worksheet_submissions")
        .select("*")
        .eq("student_id", user!.id);
      if (error) {
        console.error("Error fetching my submissions:", error);
        return [];
      }
      return data || [];
    },
  });

  const getSubmissionFor = (worksheetId: string | undefined) =>
    mySubmissions.find((s: any) => s.worksheet_id === worksheetId) || null;

  const handleFileUpload = async (ws: WorksheetAssignment, file: File) => {
    if (!user?.id) return;
    const MAX_FILE_SIZE_BYTES = 50 * 1024 * 1024; // 50MB cap (matches Supabase bucket limit)
    if (file.size > MAX_FILE_SIZE_BYTES) {
      toast.error(`File is too large (${(file.size / (1024 * 1024)).toFixed(1)}MB). Max allowed size is 50MB.`);
      return;
    }
    const ALLOWED_EXTENSIONS = [".pdf", ".doc", ".docx", ".jpg", ".jpeg", ".png", ".tiff", ".tif"];
    const ALLOWED_MIME_TYPES = [
      "application/pdf",
      "application/msword",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "image/jpeg",
      "image/png",
      "image/tiff",
    ];
    const fileExt = file.name.slice(file.name.lastIndexOf(".")).toLowerCase();
    const isAllowedExt = ALLOWED_EXTENSIONS.includes(fileExt);
    const isAllowedMime = !file.type || ALLOWED_MIME_TYPES.includes(file.type);
    if (!isAllowedExt || !isAllowedMime) {
      toast.error("Unsupported file type. Please upload a PDF, DOC, DOCX, JPG, JPEG, PNG, or TIFF file.");
      return;
    }
    const isIntact = await verifyFileIntegrity(file);
    if (!isIntact) {
      toast.error("This file appears to be corrupted or doesn't match its file type. Please choose a different file.");
      return;
    }
    setUploadingId(ws.id);
    try {
      const existing = getSubmissionFor(ws.worksheets?.id);
      const uploadPromise = uploadAnswerFile(ws, file, user.id, profile, existing?.id);
      const timeoutPromise = new Promise<null>((resolve) => setTimeout(() => resolve(null), 300000)); // 5 min, enough for 50MB on slow connections
      const result = await Promise.race([uploadPromise, timeoutPromise]);
      if (result) {
        toast.success("Answer file uploaded and submitted to your teacher!");
        queryClient.invalidateQueries({ queryKey: ["student-all-worksheet-submissions", user.id] });
      } else {
        toast.error("Upload timed out. Please check your internet connection and try again.");
      }
    } finally {
      setUploadingId(null);
    }
  };

  const handleRemoveFile = async (ws: WorksheetAssignment) => {
    const submission = getSubmissionFor(ws.worksheets?.id);
    if (!submission?.id || !submission?.answer_file_url) return;
    if (submission.status === "reviewed") {
      toast.error("This submission has already been reviewed and can't be changed.");
      return;
    }
    setRemovingId(ws.id);
    try {
      const ok = await removeAnswerFile(submission.id, submission.answer_file_url);
      if (ok) {
        toast.success("Uploaded file removed.");
        queryClient.invalidateQueries({ queryKey: ["student-all-worksheet-submissions", user?.id] });
      }
    } finally {
      setRemovingId(null);
    }
  };


  // Submission for whichever worksheet is currently open in the Practice dialog
  const existingSubmission = getSubmissionFor(practiceWorksheet?.worksheets?.id);
  const submissionLoading = false; // mySubmissions already loaded above; no separate fetch needed

  // Preload saved answers when a submission already exists
  useEffect(() => {
    if (existingSubmission?.answers) {
      setActivityAnswers(existingSubmission.answers as Record<number, string>);
    } else {
      setActivityAnswers({});
    }
  }, [existingSubmission]);

  const handleSubmitWorksheetAnswers = async () => {
    if (!practiceWorksheet?.worksheets?.id || !user?.id) return;
    setIsSubmittingWorksheet(true);
    try {
      const payload = {
        worksheet_id: practiceWorksheet.worksheets.id,
        assignment_id: practiceWorksheet.id,
        student_id: user.id,
        student_name: profile?.full_name || null,
        class_level: practiceWorksheet.class_level,
        section: practiceWorksheet.section,
        school_id: profile?.school_id || null,
        answers: activityAnswers,
        status: "submitted",
        submitted_at: new Date().toISOString(),
      };

      if (existingSubmission?.id) {
        const { error } = await supabase
          .from("worksheet_submissions")
          .update({ answers: activityAnswers, submitted_at: new Date().toISOString(), status: "submitted" })
          .eq("id", existingSubmission.id);
        if (error) throw new Error(error.message);
        toast.success("Your answers have been updated!");
      } else {
        const { error } = await supabase
          .from("worksheet_submissions")
          .insert([payload] as any);
        if (error) throw new Error(error.message);
        toast.success("Worksheet submitted!");
      }

      queryClient.invalidateQueries({
        queryKey: ["student-all-worksheet-submissions", user.id],
      });
      markWorksheetNotificationAsRead(practiceWorksheet.id);
      setPracticeWorksheet(null);
    } catch (err: any) {
      console.error("Failed to submit worksheet:", err);
      toast.error(`Failed to submit: ${err.message || "Unknown error"}`);
    } finally {
      setIsSubmittingWorksheet(false);
    }
  };

  const activities = practiceWorksheet?.worksheets?.worksheet_content
    ? parseWorksheetActivities(practiceWorksheet.worksheets.worksheet_content)
    : [];

  return (
    <AppLayout>
      <div className="min-h-screen relative overflow-x-hidden">
        <div className="absolute top-16 right-10 w-56 h-56 rounded-full bg-indigo-300 opacity-[0.12] blur-3xl pointer-events-none" />
        <div className="absolute top-96 left-6 w-64 h-64 rounded-full bg-violet-300 opacity-[0.10] blur-3xl pointer-events-none" />
        <div className="absolute bottom-24 right-1/4 w-48 h-48 rounded-full bg-indigo-200 opacity-[0.10] blur-3xl pointer-events-none" />

        <div className="relative z-10 space-y-5 p-4 md:p-6 max-w-5xl mx-auto">
          {/* Header */}
          <div className="rounded-2xl p-5 md:p-6 relative overflow-hidden bg-gradient-to-r from-indigo-600 to-violet-600 shadow-lg">
            <div className="absolute -right-6 -top-6 w-32 h-32 bg-white/10 rounded-full" />
            <div className="absolute right-16 top-8 w-16 h-16 bg-white/10 rounded-full" />
            <div className="relative flex items-center gap-3 md:gap-4">
              <div className="w-10 h-10 md:w-12 md:h-12 bg-white/20 rounded-xl flex items-center justify-center shrink-0">
                <FileText className="h-5 w-5 md:h-6 md:w-6 text-white" />
              </div>
              <div>
                <h1 className="text-xl md:text-2xl font-bold text-white">Worksheets</h1>
                <p className="text-indigo-100 text-xs md:text-sm mt-0.5">Download, view, or practice your assigned worksheets</p>
              </div>
            </div>
          </div>

          {worksheetsLoading ? (
            <div className="flex items-center justify-center py-16 text-muted-foreground gap-2">
              <Loader2 className="h-4 w-4 animate-spin" /> Loading worksheets...
            </div>
          ) : assignedWorksheets.length === 0 ? (
            <Card className="border-2 border-dashed border-indigo-200 bg-gradient-to-b from-indigo-50/50 to-white rounded-2xl">
              <CardContent className="py-16 text-center">
                <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-indigo-500 to-violet-500 flex items-center justify-center mx-auto mb-4 shadow-md shadow-indigo-200">
                  <FileText className="h-7 w-7 text-white" />
                </div>
                <h3 className="text-base font-semibold text-slate-800 mb-1">No worksheets assigned</h3>
                <p className="text-sm text-muted-foreground max-w-sm mx-auto">
                  Worksheets assigned by your teacher will appear here.
                </p>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-3">
              {assignedWorksheets.map((ws) => (
                <Card key={ws.id} className="border border-indigo-100 rounded-2xl shadow-sm overflow-hidden hover:shadow-md transition-shadow">
                  <div className="h-1 bg-gradient-to-r from-indigo-400 to-violet-400" />
                  <CardContent className="p-4 flex flex-col gap-3">
                    <div className="flex items-center justify-between gap-4 flex-wrap">
                      <div className="flex-1 min-w-[250px]">
                        <div className="flex items-center gap-2 flex-wrap mb-2">
                          <h3 className="font-semibold text-foreground">
                            {ws.worksheets?.topic || ws.worksheets?.chapter || "Worksheet"}
                          </h3>
                          {ws.worksheets?.subject && (
                            <Badge variant="outline" className="text-xs border-indigo-200 text-indigo-700 bg-indigo-50/50">{ws.worksheets.subject}</Badge>
                          )}
                        </div>
                        <div className="flex items-center gap-3 text-xs text-muted-foreground flex-wrap">
                          {ws.worksheets?.chapter && <span>Chapter: {ws.worksheets.chapter}</span>}
                          {ws.worksheets?.subtopic && <span>Subtopic: {ws.worksheets.subtopic}</span>}
                          {ws.due_date && <span>Due: {new Date(ws.due_date).toLocaleDateString()}</span>}
                        </div>
                      </div>
                    </div>

                    {/* Four action buttons, directly on the card */}
                    <div className="flex gap-2 flex-wrap pt-3 border-t border-indigo-50">
                      <Button
                        size="sm"
                        className="gap-2 bg-green-600 hover:bg-green-700 rounded-xl"
                        onClick={() => downloadWorksheetPDF(ws, profile)}
                      >
                        <Download className="h-4 w-4" /> Download PDF
                      </Button>
                      <Button
                        size="sm"
                        className="gap-2 bg-purple-600 hover:bg-purple-700 rounded-xl"
                        disabled={!ws.worksheets?.image_url}
                        onClick={() => downloadWorksheetImage(ws)}
                      >
                        <ImageIcon className="h-4 w-4" />
                        {ws.worksheets?.image_url ? "Download Worksheet Image" : "Image generating..."}
                      </Button>
                      <Button
                        size="sm"
                        className="gap-2 bg-indigo-600 hover:bg-indigo-700 rounded-xl"
                        onClick={() => setPracticeWorksheet(ws)}
                      >
                        <PenLine className="h-4 w-4" /> Practice Worksheet
                      </Button>

                      <input
                        type="file"
                        id={`answer-file-${ws.id}`}
                        accept=".pdf,.doc,.docx,.jpg,.jpeg,.png,.tiff,.tif"
                        className="hidden"
                        onChange={(e) => {
                          const file = e.target.files?.[0];
                          if (file) handleFileUpload(ws, file);
                          e.target.value = ""; // allow re-uploading the same filename later
                        }}
                      />
                      <Button
                        size="sm"
                        variant="outline"
                        className="gap-2 rounded-xl border-indigo-200 text-indigo-700 hover:bg-indigo-50"
                        disabled={uploadingId === ws.id}
                        onClick={() => document.getElementById(`answer-file-${ws.id}`)?.click()}
                      >
                        {uploadingId === ws.id ? (
                          <Loader2 className="h-4 w-4 animate-spin" />
                        ) : (
                          <Upload className="h-4 w-4" />
                        )}
                        Upload Answer File
                      </Button>

                      {getSubmissionFor(ws.worksheets?.id)?.answer_file_url && (
                        <Badge variant="outline" className="text-xs gap-1.5 self-center pr-1 border-indigo-200 bg-indigo-50/50">
                          <Paperclip className="h-3 w-3" />
                          {getSubmissionFor(ws.worksheets?.id)?.answer_file_name || "File uploaded"}
                          <Check className="h-3 w-3 text-emerald-600" />
                          {getSubmissionFor(ws.worksheets?.id)?.status !== "reviewed" && (
                            <button
                              type="button"
                              onClick={() => handleRemoveFile(ws)}
                              disabled={removingId === ws.id}
                              className="ml-1 rounded-full hover:bg-destructive/10 p-0.5 text-muted-foreground hover:text-destructive transition-colors"
                              aria-label="Remove uploaded file"
                            >
                              {removingId === ws.id ? (
                                <Loader2 className="h-3 w-3 animate-spin" />
                              ) : (
                                <X className="h-3 w-3" />
                              )}
                            </button>
                          )}
                        </Badge>
                      )}
                    </div>

                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Practice Worksheet Dialog — answer boxes only, nothing else */}
      <Dialog open={!!practiceWorksheet} onOpenChange={(open) => !open && setPracticeWorksheet(null)}>
        <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto rounded-2xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <PenLine className="h-5 w-5 text-indigo-600" />
              {practiceWorksheet?.worksheets?.topic || practiceWorksheet?.worksheets?.chapter || "Practice Worksheet"}
            </DialogTitle>
          </DialogHeader>

          {practiceWorksheet && (
            <div className="space-y-4">
              <div className="flex items-center gap-2 flex-wrap text-sm">
                <Badge variant="outline" className="text-xs border-indigo-200 text-indigo-700 bg-indigo-50/50">
                  {practiceWorksheet.class_level} · Section {practiceWorksheet.section}
                </Badge>
                {practiceWorksheet.worksheets?.subject && (
                  <Badge variant="outline" className="text-xs border-indigo-200 text-indigo-700 bg-indigo-50/50">{practiceWorksheet.worksheets.subject}</Badge>
                )}
                {existingSubmission?.status === "reviewed" ? (
                  <Badge className="bg-emerald-100 text-emerald-700 border-emerald-200 text-xs gap-1">
                    <Check className="h-3 w-3" /> Reviewed by teacher
                  </Badge>
                ) : existingSubmission?.status === "submitted" ? (
                  <Badge className="bg-indigo-100 text-indigo-700 border-indigo-200 text-xs">Submitted — pending review</Badge>
                ) : null}
              </div>

              {existingSubmission?.answer_file_url && (
                <div className="p-3 rounded-xl bg-indigo-50/50 border border-indigo-100 flex items-center gap-2 text-sm">
                  <Paperclip className="h-4 w-4 text-muted-foreground" />
                  <span>You've also uploaded a file: </span>
                  <a
                    href={existingSubmission.answer_file_url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-indigo-600 underline font-medium"
                  >
                    {existingSubmission.answer_file_name || "View file"}
                  </a>
                  {existingSubmission.status !== "reviewed" && practiceWorksheet && (
                    <button
                      type="button"
                      onClick={() => handleRemoveFile(practiceWorksheet)}
                      disabled={removingId === practiceWorksheet.id}
                      className="ml-auto text-xs text-destructive hover:underline"
                    >
                      {removingId === practiceWorksheet.id ? "Removing..." : "Remove"}
                    </button>
                  )}
                </div>
              )}

              {existingSubmission?.status === "reviewed" && existingSubmission?.teacher_feedback && (
                <div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-sm text-emerald-800">
                  <p className="font-semibold mb-1">Teacher feedback:</p>
                  <p>{existingSubmission.teacher_feedback}</p>
                </div>
              )}

              {submissionLoading ? (
                <div className="flex items-center justify-center py-8 text-muted-foreground gap-2">
                  <Loader2 className="h-4 w-4 animate-spin" /> Loading your saved answers...
                </div>
              ) : activities.length === 0 ? (
                <p className="text-sm text-muted-foreground">Could not load worksheet activities.</p>
              ) : (
                activities.map((activity, idx) => (
                  <div key={idx} className="border border-indigo-100 rounded-xl p-4 bg-card space-y-3">
                    <div className="prose prose-sm max-w-none">
                      <ReactMarkdown remarkPlugins={[remarkGfm]}>{activity}</ReactMarkdown>
                    </div>
                    <div>
                      <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1.5 block">
                        Your Answer
                      </label>
                      <Textarea
                        value={activityAnswers[idx] || ""}
                        onChange={(e) =>
                          setActivityAnswers((prev) => ({ ...prev, [idx]: e.target.value }))
                        }
                        placeholder="Write your answer here..."
                        rows={4}
                        className="bg-background rounded-xl"
                      />
                    </div>
                  </div>
                ))
              )}
            </div>
          )}

          <DialogFooter>
            <Button variant="outline" className="rounded-xl" onClick={() => setPracticeWorksheet(null)} disabled={isSubmittingWorksheet}>
              Cancel
            </Button>
            <Button
              onClick={handleSubmitWorksheetAnswers}
              disabled={isSubmittingWorksheet || activities.length === 0}
              className="gap-2 bg-indigo-600 hover:bg-indigo-700 rounded-xl"
            >
              {isSubmittingWorksheet ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
              {existingSubmission ? "Update Answers" : "Submit Worksheet"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </AppLayout>
  );
}