-- ============================================================================
-- STUDENT MASTERY ENGINE 2.0
-- subject (books) -> chapter (curriculum_chapters) -> topic (topics)
--   -> concept (subtopics) -> learning_objective (NEW) -> student_mastery (NEW, BKT)
--
-- This migration is additive only. It does NOT touch books/units/
-- curriculum_chapters/topics/subtopics (owned by the textbook-engine
-- ingestion pipeline) except to read from them via FKs.
--
-- Safety net: those five tables exist live in Supabase but are not present
-- in this repo's tracked migrations. We recreate them with IF NOT EXISTS so
-- a fresh environment (or CI) can run this migration cleanly; on your real
-- project these statements will simply no-op since the tables already exist.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0. SAFETY NET: curriculum tables (no-op if they already exist)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.books (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_name text NOT NULL,
  class_name text,
  subject text,
  curriculum text,
  school_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.units (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id bigint NOT NULL REFERENCES public.books(id) ON DELETE CASCADE,
  unit_name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.curriculum_chapters (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id bigint NOT NULL REFERENCES public.units(id) ON DELETE CASCADE,
  chapter_name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.topics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapter_id bigint NOT NULL REFERENCES public.curriculum_chapters(id) ON DELETE CASCADE,
  topic_name text NOT NULL,
  topic_code text,
  topic_description text,
  display_order int DEFAULT 1,
  status text DEFAULT 'ACTIVE',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.subtopics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id bigint NOT NULL REFERENCES public.topics(id) ON DELETE CASCADE,
  subtopic_name text NOT NULL,
  subtopic_description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 1. LEARNING OBJECTIVES (finest curriculum level, AI-generated per concept)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.learning_objectives (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subtopic_id bigint NOT NULL REFERENCES public.subtopics(id) ON DELETE CASCADE,
  objective_text text NOT NULL,
  bloom_level text CHECK (bloom_level IN ('remember','understand','apply','analyze','evaluate','create')),
  difficulty text NOT NULL DEFAULT 'medium' CHECK (difficulty IN ('easy','medium','hard')),
  display_order int NOT NULL DEFAULT 1,
  ai_generated boolean NOT NULL DEFAULT true,
  generation_model text,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','archived')),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (subtopic_id, objective_text)
);

CREATE INDEX IF NOT EXISTS idx_learning_objectives_subtopic ON public.learning_objectives(subtopic_id);

-- ---------------------------------------------------------------------------
-- 2. BKT MODEL PARAMETERS (per learning objective; sane defaults on insert)
--    P(L0) = prior mastery, P(T) = transit/learning rate,
--    P(S)  = slip (wrong despite mastery), P(G) = guess (right despite gap)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mastery_bkt_params (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  learning_objective_id bigint NOT NULL UNIQUE REFERENCES public.learning_objectives(id) ON DELETE CASCADE,
  p_init numeric NOT NULL DEFAULT 0.30 CHECK (p_init BETWEEN 0 AND 1),
  p_transit numeric NOT NULL DEFAULT 0.15 CHECK (p_transit BETWEEN 0 AND 1),
  p_slip numeric NOT NULL DEFAULT 0.10 CHECK (p_slip BETWEEN 0 AND 1),
  p_guess numeric NOT NULL DEFAULT 0.20 CHECK (p_guess BETWEEN 0 AND 1),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Auto-create default BKT params whenever a learning objective is inserted,
-- with defaults tuned slightly by difficulty (harder => lower guess/slip lenience).
CREATE OR REPLACE FUNCTION public.seed_default_bkt_params()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO public.mastery_bkt_params (learning_objective_id, p_init, p_transit, p_slip, p_guess)
  VALUES (
    NEW.id,
    0.30,
    0.15,
    CASE NEW.difficulty WHEN 'hard' THEN 0.15 WHEN 'easy' THEN 0.08 ELSE 0.10 END,
    CASE NEW.difficulty WHEN 'hard' THEN 0.12 WHEN 'easy' THEN 0.25 ELSE 0.20 END
  )
  ON CONFLICT (learning_objective_id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_seed_default_bkt_params ON public.learning_objectives;
CREATE TRIGGER trg_seed_default_bkt_params
AFTER INSERT ON public.learning_objectives
FOR EACH ROW EXECUTE FUNCTION public.seed_default_bkt_params();

-- ---------------------------------------------------------------------------
-- 3. STUDENT MASTERY (current BKT state per student per learning objective)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.student_mastery (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  learning_objective_id bigint NOT NULL REFERENCES public.learning_objectives(id) ON DELETE CASCADE,
  p_mastery numeric NOT NULL DEFAULT 0.30 CHECK (p_mastery BETWEEN 0 AND 1),
  opportunities_count int NOT NULL DEFAULT 0,
  correct_count int NOT NULL DEFAULT 0,
  last_evidence_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (student_id, learning_objective_id)
);

CREATE INDEX IF NOT EXISTS idx_student_mastery_student ON public.student_mastery(student_id);
CREATE INDEX IF NOT EXISTS idx_student_mastery_objective ON public.student_mastery(learning_objective_id);

-- Convenience view: adds a human status label without generated-column edge cases
CREATE OR REPLACE VIEW public.student_mastery_labeled AS
SELECT
  sm.*,
  CASE
    WHEN sm.opportunities_count = 0 THEN 'not_assessed'
    WHEN sm.p_mastery >= 0.85 THEN 'mastered'
    WHEN sm.p_mastery >= 0.60 THEN 'proficient'
    WHEN sm.p_mastery >= 0.35 THEN 'developing'
    ELSE 'beginning'
  END AS mastery_status
FROM public.student_mastery sm;

-- ---------------------------------------------------------------------------
-- 4. EVIDENCE LOG (append-only audit trail; every graded attempt lands here)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mastery_evidence_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  learning_objective_id bigint NOT NULL REFERENCES public.learning_objectives(id) ON DELETE CASCADE,
  is_correct boolean NOT NULL,
  source text NOT NULL CHECK (source IN ('mcq','homework','worksheet','ai_tutor','diagnostic','manual')),
  source_id uuid,
  p_mastery_before numeric NOT NULL,
  p_mastery_after numeric NOT NULL,
  responded_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mastery_evidence_student ON public.mastery_evidence_log(student_id, responded_at DESC);
CREATE INDEX IF NOT EXISTS idx_mastery_evidence_objective ON public.mastery_evidence_log(learning_objective_id);

-- ---------------------------------------------------------------------------
-- 5. CORE ENGINE: record_mastery_evidence()
--    Standard Bayesian Knowledge Tracing update, done atomically in SQL so
--    concurrent submissions (e.g. two quick MCQ answers) can't race/clobber
--    each other. SECURITY DEFINER so it can be called safely via RPC from
--    an edge function using the caller's JWT (RLS on the underlying tables
--    stays locked down to SELECT-only for normal roles; only this function,
--    and the service role, can write mastery state).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.record_mastery_evidence(
  p_student_id uuid,
  p_learning_objective_id bigint,
  p_is_correct boolean,
  p_source text,
  p_source_id uuid DEFAULT NULL
)
RETURNS TABLE (p_mastery_before numeric, p_mastery_after numeric)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_params RECORD;
  v_prior numeric;
  v_posterior numeric;
  v_next numeric;
  v_denominator numeric;
BEGIN
  -- BKT parameters for this objective (falls back to global defaults if missing)
  SELECT p_init, p_transit, p_slip, p_guess INTO v_params
  FROM public.mastery_bkt_params WHERE learning_objective_id = p_learning_objective_id;

  IF NOT FOUND THEN
    v_params := ROW(0.30, 0.15, 0.10, 0.20);
  END IF;

  -- Current mastery estimate (or the prior if this student has never attempted it)
  SELECT p_mastery INTO v_prior
  FROM public.student_mastery
  WHERE student_id = p_student_id AND learning_objective_id = p_learning_objective_id;

  IF NOT FOUND THEN
    v_prior := v_params.p_init;
  END IF;

  -- Bayes update on observed correctness
  IF p_is_correct THEN
    v_denominator := v_prior * (1 - v_params.p_slip) + (1 - v_prior) * v_params.p_guess;
    v_posterior := CASE WHEN v_denominator = 0 THEN v_prior
                         ELSE (v_prior * (1 - v_params.p_slip)) / v_denominator END;
  ELSE
    v_denominator := v_prior * v_params.p_slip + (1 - v_prior) * (1 - v_params.p_guess);
    v_posterior := CASE WHEN v_denominator = 0 THEN v_prior
                         ELSE (v_prior * v_params.p_slip) / v_denominator END;
  END IF;

  -- Learning transition: even a wrong answer creates a learning opportunity
  v_next := v_posterior + (1 - v_posterior) * v_params.p_transit;
  v_next := GREATEST(0.01, LEAST(0.99, v_next));

  INSERT INTO public.student_mastery AS sm
    (student_id, learning_objective_id, p_mastery, opportunities_count, correct_count, last_evidence_at, updated_at)
  VALUES
    (p_student_id, p_learning_objective_id, v_next, 1, CASE WHEN p_is_correct THEN 1 ELSE 0 END, now(), now())
  ON CONFLICT (student_id, learning_objective_id) DO UPDATE SET
    p_mastery = v_next,
    opportunities_count = sm.opportunities_count + 1,
    correct_count = sm.correct_count + CASE WHEN p_is_correct THEN 1 ELSE 0 END,
    last_evidence_at = now(),
    updated_at = now();

  INSERT INTO public.mastery_evidence_log
    (student_id, learning_objective_id, is_correct, source, source_id, p_mastery_before, p_mastery_after)
  VALUES
    (p_student_id, p_learning_objective_id, p_is_correct, p_source, p_source_id, v_prior, v_next);

  RETURN QUERY SELECT v_prior, v_next;
END;
$$;

-- ---------------------------------------------------------------------------
-- 6. ROLLUP: get_student_mastery_tree()
--    subject -> chapter -> topic -> concept -> learning_objective, nested
--    JSON, weighted bottom-up by objective count. Unattempted objectives
--    fall back to their BKT prior (p_init) so the tree is always complete;
--    "attempted_count" lets the UI distinguish "not yet assessed" from
--    "assessed and weak".
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_student_mastery_tree(
  p_student_id uuid,
  p_book_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH lo AS (
    SELECT
      lo.id AS learning_objective_id,
      lo.subtopic_id,
      lo.objective_text,
      lo.bloom_level,
      lo.difficulty,
      COALESCE(sml.p_mastery, bp.p_init, 0.30) AS p_mastery,
      COALESCE(sml.opportunities_count, 0) AS opportunities_count,
      COALESCE(sml.mastery_status, 'not_assessed') AS mastery_status,
      sml.last_evidence_at
    FROM public.learning_objectives lo
    LEFT JOIN public.mastery_bkt_params bp ON bp.learning_objective_id = lo.id
    LEFT JOIN public.student_mastery_labeled sml
      ON sml.learning_objective_id = lo.id AND sml.student_id = p_student_id
    WHERE lo.status = 'active'
  ),
  concept AS (
    SELECT
      st.id AS subtopic_id, st.subtopic_name, st.topic_id,
      AVG(lo.p_mastery) AS p_mastery,
      COUNT(*) AS objective_count,
      COUNT(*) FILTER (WHERE lo.opportunities_count > 0) AS attempted_count,
      MAX(lo.last_evidence_at) AS last_evidence_at,
      jsonb_agg(jsonb_build_object(
        'id', lo.learning_objective_id,
        'text', lo.objective_text,
        'bloom_level', lo.bloom_level,
        'difficulty', lo.difficulty,
        'p_mastery', round(lo.p_mastery::numeric, 3),
        'status', lo.mastery_status,
        'opportunities', lo.opportunities_count
      ) ORDER BY lo.learning_objective_id) AS objectives
    FROM public.subtopics st
    JOIN lo ON lo.subtopic_id = st.id
    GROUP BY st.id, st.subtopic_name, st.topic_id
  ),
  topic AS (
    SELECT
      t.id AS topic_id, t.topic_name, t.chapter_id,
      AVG(concept.p_mastery) AS p_mastery,
      SUM(concept.objective_count) AS objective_count,
      SUM(concept.attempted_count) AS attempted_count,
      MAX(concept.last_evidence_at) AS last_evidence_at,
      jsonb_agg(jsonb_build_object(
        'id', concept.subtopic_id,
        'name', concept.subtopic_name,
        'p_mastery', round(concept.p_mastery::numeric, 3),
        'objective_count', concept.objective_count,
        'attempted_count', concept.attempted_count,
        'objectives', concept.objectives
      ) ORDER BY concept.subtopic_id) AS concepts
    FROM public.topics t
    JOIN concept ON concept.topic_id = t.id
    GROUP BY t.id, t.topic_name, t.chapter_id
  ),
  chapter AS (
    SELECT
      c.id AS chapter_id, c.chapter_name, c.unit_id,
      AVG(topic.p_mastery) AS p_mastery,
      SUM(topic.objective_count) AS objective_count,
      SUM(topic.attempted_count) AS attempted_count,
      MAX(topic.last_evidence_at) AS last_evidence_at,
      jsonb_agg(jsonb_build_object(
        'id', topic.topic_id,
        'name', topic.topic_name,
        'p_mastery', round(topic.p_mastery::numeric, 3),
        'objective_count', topic.objective_count,
        'attempted_count', topic.attempted_count,
        'concepts', topic.concepts
      ) ORDER BY topic.topic_id) AS topics
    FROM public.curriculum_chapters c
    JOIN topic ON topic.chapter_id = c.id
    GROUP BY c.id, c.chapter_name, c.unit_id
  ),
  subject AS (
    SELECT
      b.id AS book_id, b.subject, b.class_name, b.curriculum,
      AVG(chapter.p_mastery) AS p_mastery,
      SUM(chapter.objective_count) AS objective_count,
      SUM(chapter.attempted_count) AS attempted_count,
      MAX(chapter.last_evidence_at) AS last_evidence_at,
      jsonb_agg(jsonb_build_object(
        'id', chapter.chapter_id,
        'name', chapter.chapter_name,
        'p_mastery', round(chapter.p_mastery::numeric, 3),
        'objective_count', chapter.objective_count,
        'attempted_count', chapter.attempted_count,
        'topics', chapter.topics
      ) ORDER BY chapter.chapter_id) AS chapters
    FROM public.books b
    JOIN public.units u ON u.book_id = b.id
    JOIN chapter ON chapter.unit_id = u.id
    WHERE (p_book_id IS NULL OR b.id = p_book_id)
    GROUP BY b.id, b.subject, b.class_name, b.curriculum
  )
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'book_id', subject.book_id,
    'subject', subject.subject,
    'class_name', subject.class_name,
    'curriculum', subject.curriculum,
    'p_mastery', round(subject.p_mastery::numeric, 3),
    'objective_count', subject.objective_count,
    'attempted_count', subject.attempted_count,
    'last_evidence_at', subject.last_evidence_at,
    'chapters', subject.chapters
  ) ORDER BY subject.subject), '[]'::jsonb)
  FROM subject;
$$;

-- ---------------------------------------------------------------------------
-- 7. ROLLUP: get_class_mastery() — teacher view, aggregated across a roster
--    Flags weak concepts (avg p_mastery < 0.5 across attempted students).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_class_mastery(
  p_student_ids uuid[],
  p_book_id bigint
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH per_student AS (
    SELECT public.get_student_mastery_tree(sid, p_book_id) AS tree
    FROM unnest(p_student_ids) AS sid
  ),
  chapters AS (
    SELECT
      (subj->>'book_id')::bigint AS book_id,
      chap->>'id' AS chapter_id,
      chap->>'name' AS chapter_name,
      topic->>'id' AS topic_id,
      topic->>'name' AS topic_name,
      (topic->>'p_mastery')::numeric AS p_mastery,
      (topic->>'attempted_count')::int AS attempted_count
    FROM per_student,
      jsonb_array_elements(tree) AS subj,
      jsonb_array_elements(subj->'chapters') AS chap,
      jsonb_array_elements(chap->'topics') AS topic
  ),
  -- Aggregates computed here, one row per topic — no nested aggregate calls.
  topic_stats AS (
    SELECT
      chapter_id,
      chapter_name,
      topic_id,
      topic_name,
      round(AVG(p_mastery), 3) AS class_avg_mastery,
      COUNT(*) FILTER (WHERE attempted_count > 0) AS students_attempted,
      COUNT(*) AS students_total,
      (AVG(p_mastery) < 0.5) AS is_weak_spot
    FROM chapters
    GROUP BY chapter_id, chapter_name, topic_id, topic_name
  )
  -- Outer aggregate (jsonb_agg) now only ever sees plain scalar columns.
  SELECT jsonb_agg(jsonb_build_object(
    'chapter_id', chapter_id,
    'chapter_name', chapter_name,
    'topic_id', topic_id,
    'topic_name', topic_name,
    'class_avg_mastery', class_avg_mastery,
    'students_attempted', students_attempted,
    'students_total', students_total,
    'is_weak_spot', is_weak_spot
  ))
  FROM topic_stats;
$$;

-- ---------------------------------------------------------------------------
-- 8. RLS
-- ---------------------------------------------------------------------------
ALTER TABLE public.learning_objectives ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mastery_bkt_params ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_mastery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mastery_evidence_log ENABLE ROW LEVEL SECURITY;

-- learning_objectives: everyone authenticated can read active ones; only admin/teacher manage them
CREATE POLICY "Authenticated can read active learning objectives" ON public.learning_objectives FOR SELECT
  USING (status = 'active' OR public.get_user_role(auth.uid()) IN ('admin','teacher'));

CREATE POLICY "Admins and teachers manage learning objectives" ON public.learning_objectives FOR ALL
  USING (public.get_user_role(auth.uid()) IN ('admin','teacher'))
  WITH CHECK (public.get_user_role(auth.uid()) IN ('admin','teacher'));

-- mastery_bkt_params: admin/teacher only (internal tuning knobs)
CREATE POLICY "Admins and teachers manage BKT params" ON public.mastery_bkt_params FOR ALL
  USING (public.get_user_role(auth.uid()) IN ('admin','teacher'))
  WITH CHECK (public.get_user_role(auth.uid()) IN ('admin','teacher'));

-- student_mastery: read-only for students (own) and teachers/admins (all); writes go through record_mastery_evidence()
CREATE POLICY "Admins full access to student mastery" ON public.student_mastery FOR ALL
  USING (public.get_user_role(auth.uid()) = 'admin')
  WITH CHECK (public.get_user_role(auth.uid()) = 'admin');

CREATE POLICY "Teachers can read all student mastery" ON public.student_mastery FOR SELECT
  USING (public.get_user_role(auth.uid()) = 'teacher');

CREATE POLICY "Students can read own mastery" ON public.student_mastery FOR SELECT
  USING (student_id IN (SELECT id FROM public.students WHERE profile_id = auth.uid()));

-- mastery_evidence_log: same read pattern; inserts happen only via the SECURITY DEFINER function
CREATE POLICY "Admins full access to evidence log" ON public.mastery_evidence_log FOR ALL
  USING (public.get_user_role(auth.uid()) = 'admin')
  WITH CHECK (public.get_user_role(auth.uid()) = 'admin');

CREATE POLICY "Teachers can read evidence log" ON public.mastery_evidence_log FOR SELECT
  USING (public.get_user_role(auth.uid()) = 'teacher');

CREATE POLICY "Students can read own evidence log" ON public.mastery_evidence_log FOR SELECT
  USING (student_id IN (SELECT id FROM public.students WHERE profile_id = auth.uid()));

-- Let authenticated roles call the RPCs directly (functions still enforce their own logic;
-- edge functions call these with the caller's JWT via supabase-js)
GRANT EXECUTE ON FUNCTION public.record_mastery_evidence(uuid, bigint, boolean, text, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_student_mastery_tree(uuid, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_class_mastery(uuid[], bigint) TO authenticated;
