-- ============================================================================
-- KNOWLEDGE GRAPH ENGINE
-- Two prerequisite DAGs (topic-level overview + concept-level detail) plus a
-- misconceptions catalog per concept, and rollups that connect this graph to
-- the Student Mastery Engine (readiness checks, at-risk concept detection).
--
-- Distinct from the existing /knowledge-graph page (KnowledgeGraphDashboard),
-- which is a knsoft_admin-only browser for `knowledge_chunks` RAG embeddings
-- and has nothing to do with prerequisites. This migration does not touch it.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. TOPIC-LEVEL PREREQUISITES (coarse graph, whole-subject overview)
--    Edge meaning: topic_id REQUIRES prerequisite_topic_id first.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.topic_prerequisites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id bigint NOT NULL REFERENCES public.topics(id) ON DELETE CASCADE,
  prerequisite_topic_id bigint NOT NULL REFERENCES public.topics(id) ON DELETE CASCADE,
  strength numeric NOT NULL DEFAULT 0.7 CHECK (strength BETWEEN 0 AND 1),
  rationale text,
  ai_generated boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (topic_id <> prerequisite_topic_id),
  UNIQUE (topic_id, prerequisite_topic_id)
);

CREATE INDEX IF NOT EXISTS idx_topic_prereq_topic ON public.topic_prerequisites(topic_id);
CREATE INDEX IF NOT EXISTS idx_topic_prereq_prereq ON public.topic_prerequisites(prerequisite_topic_id);

-- ---------------------------------------------------------------------------
-- 2. CONCEPT-LEVEL PREREQUISITES (fine graph, matches Mastery Engine's level)
--    Edge meaning: subtopic_id REQUIRES prerequisite_subtopic_id first.
--    Not restricted to the same topic — a concept can depend on one from an
--    earlier chapter.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.concept_prerequisites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subtopic_id bigint NOT NULL REFERENCES public.subtopics(id) ON DELETE CASCADE,
  prerequisite_subtopic_id bigint NOT NULL REFERENCES public.subtopics(id) ON DELETE CASCADE,
  strength numeric NOT NULL DEFAULT 0.7 CHECK (strength BETWEEN 0 AND 1),
  rationale text,
  ai_generated boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (subtopic_id <> prerequisite_subtopic_id),
  UNIQUE (subtopic_id, prerequisite_subtopic_id)
);

CREATE INDEX IF NOT EXISTS idx_concept_prereq_subtopic ON public.concept_prerequisites(subtopic_id);
CREATE INDEX IF NOT EXISTS idx_concept_prereq_prereq ON public.concept_prerequisites(prerequisite_subtopic_id);

-- ---------------------------------------------------------------------------
-- 3. MISCONCEPTIONS CATALOG (per concept)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.concept_misconceptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subtopic_id bigint NOT NULL REFERENCES public.subtopics(id) ON DELETE CASCADE,
  misconception_text text NOT NULL,
  why_it_happens text,
  correction_hint text,
  severity text NOT NULL DEFAULT 'medium' CHECK (severity IN ('low','medium','high')),
  ai_generated boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_misconceptions_subtopic ON public.concept_misconceptions(subtopic_id);

-- ---------------------------------------------------------------------------
-- 4. CYCLE PREVENTION
--    Prerequisite graphs must stay acyclic. Before inserting/updating an
--    edge, walk the existing graph from the new prerequisite node forward;
--    if the dependent node is already reachable, this edge would close a
--    loop, so reject it.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.prevent_topic_prerequisite_cycle()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_would_cycle boolean;
BEGIN
  WITH RECURSIVE reachable AS (
    SELECT prerequisite_topic_id AS node_id
    FROM public.topic_prerequisites
    WHERE topic_id = NEW.prerequisite_topic_id
    UNION
    SELECT tp.prerequisite_topic_id
    FROM public.topic_prerequisites tp
    JOIN reachable r ON tp.topic_id = r.node_id
  )
  SELECT EXISTS (SELECT 1 FROM reachable WHERE node_id = NEW.topic_id) INTO v_would_cycle;

  IF v_would_cycle THEN
    RAISE EXCEPTION 'Adding this prerequisite would create a cycle in the topic graph (% -> ... -> %)',
      NEW.prerequisite_topic_id, NEW.topic_id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_prevent_topic_prerequisite_cycle ON public.topic_prerequisites;
CREATE TRIGGER trg_prevent_topic_prerequisite_cycle
BEFORE INSERT OR UPDATE ON public.topic_prerequisites
FOR EACH ROW EXECUTE FUNCTION public.prevent_topic_prerequisite_cycle();

CREATE OR REPLACE FUNCTION public.prevent_concept_prerequisite_cycle()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_would_cycle boolean;
BEGIN
  WITH RECURSIVE reachable AS (
    SELECT prerequisite_subtopic_id AS node_id
    FROM public.concept_prerequisites
    WHERE subtopic_id = NEW.prerequisite_subtopic_id
    UNION
    SELECT cp.prerequisite_subtopic_id
    FROM public.concept_prerequisites cp
    JOIN reachable r ON cp.subtopic_id = r.node_id
  )
  SELECT EXISTS (SELECT 1 FROM reachable WHERE node_id = NEW.subtopic_id) INTO v_would_cycle;

  IF v_would_cycle THEN
    RAISE EXCEPTION 'Adding this prerequisite would create a cycle in the concept graph (% -> ... -> %)',
      NEW.prerequisite_subtopic_id, NEW.subtopic_id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_prevent_concept_prerequisite_cycle ON public.concept_prerequisites;
CREATE TRIGGER trg_prevent_concept_prerequisite_cycle
BEFORE INSERT OR UPDATE ON public.concept_prerequisites
FOR EACH ROW EXECUTE FUNCTION public.prevent_concept_prerequisite_cycle();

-- ---------------------------------------------------------------------------
-- 5. GRAPH FETCH: get_topic_graph(book_id) — nodes + edges for the whole
--    subject's topic-level overview graph.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_topic_graph(p_book_id bigint)
RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  WITH graph_topics AS (
    SELECT t.id, t.topic_name, t.chapter_id, c.chapter_name
    FROM public.topics t
    JOIN public.curriculum_chapters c ON c.id = t.chapter_id
    JOIN public.units u ON u.id = c.unit_id
    WHERE u.book_id = p_book_id
  ),
  nodes AS (
    SELECT jsonb_agg(jsonb_build_object(
      'id', id, 'name', topic_name, 'chapter_id', chapter_id, 'chapter_name', chapter_name
    ) ORDER BY chapter_id, id) AS v
    FROM graph_topics
  ),
  edges AS (
    SELECT jsonb_agg(jsonb_build_object(
      'from', tp.prerequisite_topic_id, 'to', tp.topic_id,
      'strength', tp.strength, 'rationale', tp.rationale
    ) ORDER BY tp.id) AS v
    FROM public.topic_prerequisites tp
    WHERE tp.topic_id IN (SELECT id FROM graph_topics)
  )
  SELECT jsonb_build_object(
    'nodes', COALESCE((SELECT v FROM nodes), '[]'::jsonb),
    'edges', COALESCE((SELECT v FROM edges), '[]'::jsonb)
  );
$$;

-- ---------------------------------------------------------------------------
-- 6. GRAPH FETCH: get_concept_graph(topic_id) — nodes + edges for one
--    topic's concepts. Includes prerequisite nodes from other topics too
--    (marked external) so cross-chapter dependencies are still visible.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_concept_graph(p_topic_id bigint)
RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  WITH local_concepts AS (
    SELECT id FROM public.subtopics WHERE topic_id = p_topic_id
  ),
  relevant_edges AS (
    SELECT cp.id, cp.subtopic_id, cp.prerequisite_subtopic_id, cp.strength, cp.rationale
    FROM public.concept_prerequisites cp
    WHERE cp.subtopic_id IN (SELECT id FROM local_concepts)
       OR cp.prerequisite_subtopic_id IN (SELECT id FROM local_concepts)
  ),
  node_ids AS (
    SELECT id FROM local_concepts
    UNION
    SELECT subtopic_id FROM relevant_edges
    UNION
    SELECT prerequisite_subtopic_id FROM relevant_edges
  ),
  nodes AS (
    SELECT jsonb_agg(jsonb_build_object(
      'id', st.id, 'name', st.subtopic_name, 'topic_id', st.topic_id, 'topic_name', t.topic_name,
      'is_external', st.topic_id <> p_topic_id
    ) ORDER BY st.id) AS v
    FROM public.subtopics st
    JOIN public.topics t ON t.id = st.topic_id
    WHERE st.id IN (SELECT id FROM node_ids)
  ),
  edges AS (
    SELECT jsonb_agg(jsonb_build_object(
      'from', prerequisite_subtopic_id, 'to', subtopic_id, 'strength', strength, 'rationale', rationale
    ) ORDER BY id) AS v
    FROM relevant_edges
  ),
  misconceptions AS (
    SELECT jsonb_agg(jsonb_build_object(
      'id', cm.id, 'subtopic_id', cm.subtopic_id, 'text', cm.misconception_text,
      'why', cm.why_it_happens, 'correction', cm.correction_hint, 'severity', cm.severity
    ) ORDER BY cm.subtopic_id, cm.id) AS v
    FROM public.concept_misconceptions cm
    WHERE cm.subtopic_id IN (SELECT id FROM local_concepts)
  )
  SELECT jsonb_build_object(
    'nodes', COALESCE((SELECT v FROM nodes), '[]'::jsonb),
    'edges', COALESCE((SELECT v FROM edges), '[]'::jsonb),
    'misconceptions', COALESCE((SELECT v FROM misconceptions), '[]'::jsonb)
  );
$$;

-- ---------------------------------------------------------------------------
-- 7. BRIDGE TO MASTERY ENGINE: get_prerequisite_readiness(student, subtopic)
--    For one concept, roll up the student's current mastery across every
--    direct prerequisite (using the same "average of that concept's
--    learning objectives, falling back to BKT prior" logic as the Mastery
--    Engine's rollup), weighted by prerequisite strength.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_prerequisite_readiness(
  p_student_id uuid,
  p_subtopic_id bigint
)
RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  WITH prereqs AS (
    SELECT cp.prerequisite_subtopic_id, cp.strength, st.subtopic_name
    FROM public.concept_prerequisites cp
    JOIN public.subtopics st ON st.id = cp.prerequisite_subtopic_id
    WHERE cp.subtopic_id = p_subtopic_id
  ),
  prereq_mastery AS (
    SELECT
      p.prerequisite_subtopic_id, p.subtopic_name, p.strength,
      AVG(COALESCE(sml.p_mastery, bp.p_init, 0.30)) AS p_mastery,
      COUNT(*) FILTER (WHERE sml.opportunities_count > 0) AS attempted_count,
      COUNT(*) AS objective_count
    FROM prereqs p
    JOIN public.learning_objectives lo ON lo.subtopic_id = p.prerequisite_subtopic_id AND lo.status = 'active'
    LEFT JOIN public.mastery_bkt_params bp ON bp.learning_objective_id = lo.id
    LEFT JOIN public.student_mastery_labeled sml ON sml.learning_objective_id = lo.id AND sml.student_id = p_student_id
    GROUP BY p.prerequisite_subtopic_id, p.subtopic_name, p.strength
  ),
  summary AS (
    SELECT
      COALESCE(SUM(p_mastery * strength) / NULLIF(SUM(strength), 0), 1.0) AS readiness_score,
      COALESCE(BOOL_AND(p_mastery >= 0.5 OR attempted_count = 0), true) AS all_at_or_above_threshold,
      COUNT(*) AS prerequisite_count
    FROM prereq_mastery
  )
  SELECT jsonb_build_object(
    'subtopic_id', p_subtopic_id,
    'prerequisite_count', s.prerequisite_count,
    'readiness_score', round(s.readiness_score::numeric, 3),
    'is_ready', s.readiness_score >= 0.5,
    'prerequisites', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'subtopic_id', prerequisite_subtopic_id, 'name', subtopic_name, 'strength', strength,
        'p_mastery', round(p_mastery::numeric, 3), 'attempted', attempted_count > 0
      ) ORDER BY p_mastery ASC)
      FROM prereq_mastery
    ), '[]'::jsonb)
  )
  FROM summary s;
$$;

-- ---------------------------------------------------------------------------
-- 8. BRIDGE TO MASTERY ENGINE: get_at_risk_concepts(student, book)
--    Every concept in a subject that has learning objectives AND at least
--    one prerequisite currently below the readiness threshold. Meant for
--    teacher dashboards and the AI tutor's context (flag before assigning).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_at_risk_concepts(
  p_student_id uuid,
  p_book_id bigint
)
RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  WITH book_concepts AS (
    SELECT DISTINCT st.id AS subtopic_id, st.subtopic_name, t.id AS topic_id, t.topic_name
    FROM public.subtopics st
    JOIN public.topics t ON t.id = st.topic_id
    JOIN public.curriculum_chapters c ON c.id = t.chapter_id
    JOIN public.units u ON u.id = c.unit_id
    WHERE u.book_id = p_book_id
      AND EXISTS (SELECT 1 FROM public.learning_objectives lo WHERE lo.subtopic_id = st.id AND lo.status = 'active')
  ),
  readiness AS (
    SELECT
      bc.subtopic_id, bc.subtopic_name, bc.topic_id, bc.topic_name,
      public.get_prerequisite_readiness(p_student_id, bc.subtopic_id) AS r
    FROM book_concepts bc
    WHERE EXISTS (SELECT 1 FROM public.concept_prerequisites cp WHERE cp.subtopic_id = bc.subtopic_id)
  )
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'subtopic_id', subtopic_id, 'subtopic_name', subtopic_name,
    'topic_id', topic_id, 'topic_name', topic_name,
    'readiness_score', r->'readiness_score', 'weak_prerequisites', (
      SELECT jsonb_agg(p) FROM jsonb_array_elements(r->'prerequisites') p
      WHERE (p->>'p_mastery')::numeric < 0.5 AND (p->>'attempted')::boolean = true
    )
  ) ORDER BY (r->>'readiness_score')::numeric ASC), '[]'::jsonb)
  FROM readiness
  WHERE (r->>'is_ready')::boolean = false;
$$;

-- ---------------------------------------------------------------------------
-- 9. RLS
-- ---------------------------------------------------------------------------
ALTER TABLE public.topic_prerequisites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.concept_prerequisites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.concept_misconceptions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated can read topic prerequisites" ON public.topic_prerequisites;
CREATE POLICY "Authenticated can read topic prerequisites" ON public.topic_prerequisites FOR SELECT
  USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins and teachers manage topic prerequisites" ON public.topic_prerequisites;
CREATE POLICY "Admins and teachers manage topic prerequisites" ON public.topic_prerequisites FOR ALL
  USING (public.get_user_role(auth.uid()) IN ('admin','teacher'))
  WITH CHECK (public.get_user_role(auth.uid()) IN ('admin','teacher'));

DROP POLICY IF EXISTS "Authenticated can read concept prerequisites" ON public.concept_prerequisites;
CREATE POLICY "Authenticated can read concept prerequisites" ON public.concept_prerequisites FOR SELECT
  USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins and teachers manage concept prerequisites" ON public.concept_prerequisites;
CREATE POLICY "Admins and teachers manage concept prerequisites" ON public.concept_prerequisites FOR ALL
  USING (public.get_user_role(auth.uid()) IN ('admin','teacher'))
  WITH CHECK (public.get_user_role(auth.uid()) IN ('admin','teacher'));

DROP POLICY IF EXISTS "Authenticated can read misconceptions" ON public.concept_misconceptions;
CREATE POLICY "Authenticated can read misconceptions" ON public.concept_misconceptions FOR SELECT
  USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins and teachers manage misconceptions" ON public.concept_misconceptions;
CREATE POLICY "Admins and teachers manage misconceptions" ON public.concept_misconceptions FOR ALL
  USING (public.get_user_role(auth.uid()) IN ('admin','teacher'))
  WITH CHECK (public.get_user_role(auth.uid()) IN ('admin','teacher'));

GRANT EXECUTE ON FUNCTION public.get_topic_graph(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_concept_graph(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_prerequisite_readiness(uuid, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_at_risk_concepts(uuid, bigint) TO authenticated;
